// Generated by https://quicktype.io

// class Respuesta {
//   int id;
//   List<Cast> cast;
//   List<Cast> crew;

//   Respuesta({
//     this.id,
//     this.cast,
//     this.crew,
//   });
// }

class Cast {
  
  List<Actor> actores = [];

  Cast.fromJsonList(List<dynamic> jsonList) {

    if(jsonList == null) return;

    actores.addAll(jsonList.map((item) => Actor.fromJsonMap(item)));

    // jsonList.forEach((item) { 
      
    //   final actor = Actor.fromJsonMap(item);
    //   actores.add(actor);
    
    // });

  }

}

class Actor {
  bool adult;
  int gender;
  int id;
  Department knownForDepartment;
  String name;
  String originalName;
  double popularity;
  String profilePath;
  int castId;
  String character;
  String creditId;
  int order;
  Department department;
  String job;

  Actor({
    this.adult,
    this.gender,
    this.id,
    this.knownForDepartment,
    this.name,
    this.originalName,
    this.popularity,
    this.profilePath,
    this.castId,
    this.character,
    this.creditId,
    this.order,
    this.department,
    this.job,
  });

  Actor.fromJsonMap(Map<String, dynamic> json) {

    adult               = json['adult'];
    gender              = json['gender'];
    id                  = json['id'];
    // knownForDepartment  = json['known_for_department'];
    name                = json['name'];
    originalName        = json['original_name'];
    popularity          = json['popularity'];
    profilePath         = json['profile_path'];
    castId              = json['cast_id'];
    character           = json['character'];
    creditId            = json['credit_id'];
    order               = json['order'];
    department          = json['department'];
    job                 = json['job'];

  }

  getFoto() {

    if( profilePath == null ) {
      return 'https://www.intra-tp.com/wp-content/uploads/2017/02/no-avatar.png';
    }else{
      return 'https://image.tmdb.org/t/p/w500/$profilePath';
    }
  }
}

enum Department { ACTING, DIRECTING, WRITING, SOUND, ART, PRODUCTION, CREW, EDITING, CAMERA, COSTUME_MAKE_UP }